---
apiVersion: "v1"
data:
  keycloak-demo-server--admin-user: "${keycloak.admin.user}"
  keycloak-demo-server--admin-password: "${keycloak.admin.password}"
  keycloak-demo-server--root-url: ""
  keycloak-demo-server--host-ip: ""
metadata:
  annotations:
    expose.config.fabric8.io/url-key: "keycloak-demo-server--root-url"
    expose.config.fabric8.io/host-key: "keycloak-demo-server--host-ip"
  labels: {}
  name: "${project.artifactId}"
kind: "ConfigMap"
