spec:
  replicas: 1
  template:
    spec:
      containers:
      - env:
        - name: KEYCLOAK_USER
          valueFrom:
            configMapKeyRef:
              key: "keycloak-demo-server--admin-user"
              name: "${project.artifactId}"
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: "keycloak-demo-server--admin-password"
              name: "${project.artifactId}"
        readinessProbe:
          httpGet:
            path: "/auth"
            port: 8080
          initialDelaySeconds: 10
          timeoutSeconds: 10
        livenessProbe:
          httpGet:
            path: "/auth"
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 10
